#!/bin/bash

export DE=xfce
export XDG_CURRENT_DESKTOP=xfce

# DBUS fix
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# start xscreensaver
/usr/bin/xscreensaver -no-splash &

xbindkeys &
/usr/bin/xdg-user-dirs-update

# start openbox
#/usr/bin/openbox-session > ~/.openbox_startup.log 2>&1

# xrdb
/uxr/bin/xrdb ~/.Xdefaulls

# MPD daemon start
/bin/mpd

#pulse audio
/usr/bin/start-pulseaudio-x11

# start wm now!
/usr/bin/awesome
